// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spotify} from '../models';

export function GetSavedTracks(arg1:number,arg2:number):Promise<Array<spotify.SavedTrackRow>>;
